# Generated by Django 5.0.3 on 2024-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='apply_link',
            field=models.URLField(default='https://travelatb.com/'),
        ),
    ]
