# Generated by Django 5.0.3 on 2024-06-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='options',
        ),
        migrations.AddField(
            model_name='option',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.trip'),
        ),
    ]
