# Generated by Django 5.0.3 on 2024-06-27 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_trip_available_places_trip_date_trip_max_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.AddField(
            model_name='trip',
            name='ig_link',
            field=models.URLField(default='www.travelatb.com'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
