# Generated by Django 5.0.3 on 2024-07-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_available_places_trip_taken_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ig_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='max_places',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='taken_places',
            field=models.PositiveIntegerField(),
        ),
    ]
