# Generated by Django 5.0.3 on 2024-08-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_option_trip_alter_trip_ig_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='g_form',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('past', 'Past'), ('future', 'Future')], default='current', max_length=10),
        ),
    ]
